name: Deploy React App
on:
  push:
    branches:
      - "main"
    paths-igore:
      # изменения в '.github/workflows/*' будут проигнорированы при push
      - ".github/workflows/*"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Install deps
        run: npm ci
      - name: Test app
        run: npm run test
      - name: Lint app
        run: npm run lint
      - name: Build app
        run: npm run lint
      - name: Deploy app
        run: echo Deployment...
